spring.application.name=user-service
server.port=8081

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# PostgreSQL Database Configuration
spring.datasource.url=${USERS_DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#Super Admin Credentials
superadmin.password=${SUPERADMIN_PASSWORD}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true