# Stage 1: Build using Eclipse Temurin Maven image
FROM maven:3.8.5-eclipse-temurin-17 AS build
WORKDIR /app

COPY common-lib ./common-lib
RUN cd common-lib && mvn clean install -DskipTests

COPY service-registry ./service-registry
RUN cd service-registry && mvn clean package -DskipTests

# Stage 2: Run using the lightweight JRE image
FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY --from=build /app/service-registry/target/*.jar app.jar

EXPOSE 8761
ENTRYPOINT ["java", "-jar", "app.jar"]